name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      ######################################################
      # AWS CREDENTIALS
      ######################################################
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1

      ######################################################
      # LOGIN TO ECR
      ######################################################
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      ######################################################
      # BUILD & PUSH DOCKER IMAGES
      ######################################################

      - name: Build & Push User Service Image
        run: |
          cd corelia/services/user
          docker build -t user-service .
          docker tag user-service:latest ${{ steps.login-ecr.outputs.registry }}/user-service:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/user-service:latest

      - name: Build & Push Order Service Image
        run: |
          cd corelia/services/order
          docker build -t order-service .
          docker tag order-service:latest ${{ steps.login-ecr.outputs.registry }}/order-service:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/order-service:latest

      - name: Build & Push Payment Service Image
        run: |
          cd corelia/services/payment
          docker build -t payment-service .
          docker tag payment-service:latest ${{ steps.login-ecr.outputs.registry }}/payment-service:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/payment-service:latest

      ######################################################
      # TERRAFORM DEPLOY
      ######################################################
      - name: Terraform Init
        run: |
          cd corelia/terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd corelia/terraform
          terraform apply -auto-approve
          